krk-tasker/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :tasks, except: [:index], controller: 'projects/tasks'
  end

 

root "projects#index"

end

krk-tasker/app/models/counter.rb
class Counter
	def self.calculate_percent_complete(completed_tasks, total_tasks)
		completed_tasks.to_f / total_tasks.to_f * 100
	end
end

krk-tasker/app/models/project.rb
class Project < ActiveRecord::Base
	#scope :almost_completed, -> {where('percent_complete > 75.0')}
	validates_presence_of :title, :description, :percent_complete
    has_many :tasks
end

krk-tasker/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project

  after_update :update_percent_complete if :mark_completed?
  after_create :update_percent_complete

  scope :completed, -> { where(completed: true) }

  mount_uploader :task_file, TaskFileUploader

  def mark_completed?
  	self.completed == true
  end

  def update_percent_complete
  	project = Project.find(self.project_id)
  	count_of_completed_tasks = project.tasks.completed.count
  	count_of_total_tasks = project.tasks.count
  	project.update!(percent_complete: Counter.calculate_percent_complete(count_of_completed_tasks, count_of_total_tasks))
  end
end

krk-tasker/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

krk-tasker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:username]
  end
end

krk-tasker/app/controllers/projects/tasks_controller.rb
class Projects::TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project, only: [:show, :new, :edit, :create, :update, :destroy]

  def show
  end

  def new
  	@task = Task.new
  end

  def edit
  end

  def create
  	@task = Task.new(task_params)
  	@task.project_id = @project.id

  	respond_to do |format|
  		if @task.save
  			format.html { redirect_to project_path(@task.project_id), notice: 'Task was successfully created.' }
  			format.json { render :show, status: :created, location: @task }
  		else
  			format.html { render :new }
  			format.json { render json: @task.errors, status: :unprocessable_entity }
  		end
  	end
  end

  def update
  	respond_to do |format|
  		if @task.update(task_params)
  			format.html { redirect_to project_path(@task.project_id), notice: 'Task was successfully updated.' }
  			format.json { render :show, status: :ok, location: @task }
  		else
  			format.html { render :edit }
  			format.json { render json: @task.errors, status: :unprocessable_entity }
  		end
  	end
  end

  def destroy
  	@task.destroy
  	respond_to do |format|
  		format.html { redirect_to project_url(@task.project_id), notice: 'Task was successfully deleted.' }
  		format.json { head :no_content }
  	end
  end

  private
  	def set_task
  		@task = Task.find(params[:id])
  	end

    def set_project
      @project = Project.find(params[:project_id])
    end

  	def task_params
  		params.require(:task).permit(:title, :description, :project_id, :completed, :task_file)
  	end

end

krk-tasker/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :percent_complete)
    end
end

krk-tasker/app/helpers/application_helper.rb
module ApplicationHelper
end

krk-tasker/app/helpers/projects_helper.rb
module ProjectsHelper
end

krk-tasker/app/helpers/tasks_helper.rb
module TasksHelper
end

krk-tasker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= image_tag('penguin.png', width: '100px') %>

<% if current_user %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign Up", new_user_registration_path %>
  <%= link_to "Sign In", new_user_session_path %>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

krk-tasker/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :percent_complete %><br>
    <%= f.text_field :percent_complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

krk-tasker/app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

krk-tasker/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag('wildlife.jpg', width: '425px') %>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Percent complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.percent_complete %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

krk-tasker/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

krk-tasker/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Percent complete:</strong>
  <%= @project.percent_complete %>
</p>

<% @project.tasks.each do |task| %>
      <b>Title: </b><%= task.title %> <b>Description: </b><%= task.description %> <b>Completed: </b> <%= task.completed %> <%= link_to "File", task.task_file.to_s unless task.task_file.blank? %><hr>
<% end %>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>
<%= link_to 'New Task', new_project_task_path(@project) %>

krk-tasker/app/views/projects/tasks/_form.html.erb
<%= form_for [@project, @task] do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>

  <div class="field">
    <%= f.label :task_file %><br>
    <%= f.file_field :task_file %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

krk-tasker/app/views/projects/tasks/edit.html.erb
<h1>Edit a task</h1>

<%= render 'form' %>

krk-tasker/app/views/projects/tasks/new.html.erb
<h1>Create a new task</h1>

<%= render 'form' %>